# Generated by Django 3.2.9 on 2021-12-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
